-- 将该建表 SQL 语句，添加到 yudao-module-pdeploy-biz 模块的 test/resources/sql/create_tables.sql 文件里
CREATE TABLE IF NOT EXISTS "pdeploy_module" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "tenant_id" bigint,
    "baseline_id" bigint,
    "name" varchar,
    "module_type" int,
    "estimated_time" bigint,
    "creator" varchar DEFAULT '',
    "updater" varchar DEFAULT '',
    "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    "remark" varchar,
    "deleted" bit NOT NULL DEFAULT FALSE,
    PRIMARY KEY ("id")
) COMMENT '模块';

-- 将该删表 SQL 语句，添加到 yudao-module-pdeploy-biz 模块的 test/resources/sql/clean.sql 文件里
DELETE FROM "pdeploy_module";
